In [38]:
# Dependencies
import numpy as np
import pandas as pd
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import datetime as dt

In [3]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [4]:
# Create our session (link) from Python to the DB
session = Session(engine)

## D1: Determine the Summary Statistics for June

In [148]:
session.query(Measurement.date).limit(4).all()

[('2010-01-01'), ('2010-01-02'), ('2010-01-03'), ('2010-01-04')]

In [32]:
session.query(Measurement.tobs).all()

[(65.0),
 (63.0),
 (74.0),
 (76.0),
 (73.0),
 (70.0),
 (64.0),
 (68.0),
 (73.0),
 (64.0),
 (61.0),
 (66.0),
 (65.0),
 (68.0),
 (64.0),
 (72.0),
 (66.0),
 (66.0),
 (69.0),
 (67.0),
 (67.0),
 (71.0),
 (67.0),
 (76.0),
 (68.0),
 (72.0),
 (70.0),
 (67.0),
 (66.0),
 (67.0),
 (69.0),
 (67.0),
 (67.0),
 (64.0),
 (69.0),
 (73.0),
 (73.0),
 (69.0),
 (69.0),
 (69.0),
 (71.0),
 (61.0),
 (69.0),
 (63.0),
 (64.0),
 (65.0),
 (67.0),
 (68.0),
 (65.0),
 (76.0),
 (75.0),
 (66.0),
 (70.0),
 (72.0),
 (73.0),
 (70.0),
 (71.0),
 (72.0),
 (72.0),
 (69.0),
 (70.0),
 (73.0),
 (72.0),
 (73.0),
 (70.0),
 (71.0),
 (68.0),
 (70.0),
 (72.0),
 (69.0),
 (68.0),
 (74.0),
 (72.0),
 (72.0),
 (73.0),
 (74.0),
 (73.0),
 (73.0),
 (74.0),
 (74.0),
 (74.0),
 (71.0),
 (72.0),
 (75.0),
 (75.0),
 (75.0),
 (75.0),
 (73.0),
 (73.0),
 (71.0),
 (71.0),
 (68.0),
 (70.0),
 (71.0),
 (74.0),
 (71.0),
 (75.0),
 (76.0),
 (75.0),
 (75.0),
 (76.0),
 (76.0),
 (76.0),
 (77.0),
 (77.0),
 (73.0),
 (74.0),
 (76.0),
 (76.0),
 (80.0),
 (74.0),
 (77.0),
 (77.0),
 (76.0),
 (77.0),
 (78.0),
 (78.0),
 (75.0),
 (73.0),
 (77.0),
 (76.0),
 (77.0),
 (77.0),
 (78.0),
 (75.0),
 (77.0),
 (77.0),
 (77.0),
 (76.0),
 (75.0),
 (77.0),
 (77.0),
 (77.0),
 (78.0),
 (76.0),
 (78.0),
 (76.0),
 (77.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (79.0),
 (78.0),
 (78.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (77.0),
 (77.0),
 (82.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (77.0),
 (76.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (75.0),
 (77.0),
 (77.0),
 (78.0),
 (78.0),
 (76.0),
 (74.0),
 (76.0),
 (74.0),
 (76.0),
 (78.0),
 (77.0),
 (80.0),
 (78.0),
 (76.0),
 (77.0),
 (77.0),
 (80.0),
 (78.0),
 (80.0),
 (79.0),
 (78.0),
 (79.0),
 (78.0),
 (79.0),
 (78.0),
 (77.0),
 (77.0),
 (76.0),
 (77.0),
 (77.0),
 (75.0),
 (75.0),
 (80.0),
 (77.0),
 (78.0),
 (78.0),
 (77.0),
 (76.0),
 (78.0),
 (78.0),
 (76.0),
 (76.0),
 (74.0),
 (77.0),
 (79.0),
 (79.0),
 (79.0),
 (75.0),
 (87.0),
 (78.0),
 (76.0),
 (78.0),
 (78.0),
 (79.0),
 (78.0),
 (78.0),
 (80.0),
 (77.0),
 (76.0),
 (78.0),
 (77.0),
 (77.0),
 (77.0),
 (76.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (74.0),
 (78.0),
 (79.0),
 (77.0),
 (79.0),
 (78.0),
 (78.0),
 (78.0),
 (79.0),
 (76.0),
 (78.0),
 (78.0),
 (79.0),
 (74.0),
 (75.0),
 (75.0),
 (78.0),
 (73.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (80.0),
 (79.0),
 (79.0),
 (78.0),
 (78.0),
 (78.0),
 (77.0),
 (79.0),
 (78.0),
 (78.0),
 (77.0),
 (76.0),
 (76.0),
 (72.0),
 (74.0),
 (80.0),
 (77.0),
 (75.0),
 (78.0),
 (78.0),
 (76.0),
 (79.0),
 (78.0),
 (78.0),
 (77.0),
 (76.0),
 (75.0),
 (73.0),
 (73.0),
 (77.0),
 (76.0),
 (77.0),
 (76.0),
 (73.0),
 (73.0),
 (77.0),
 (77.0),
 (76.0),
 (73.0),
 (73.0),
 (72.0),
 (69.0),
 (69.0),
 (68.0),
 (69.0),
 (76.0),
 (76.0),
 (75.0),
 (74.0),
 (69.0),
 (74.0),
 (76.0),
 (74.0),
 (74.0),
 (64.0),
 (64.0),
 (67.0),
 (77.0),
 (66.0),
 (69.0),
 (68.0),
 (68.0),
 (71.0),
 (74.0),
 (67.0),
 (66.0),
 (69.0),
 (71.0),
 (70.0),
 (70.0),
 (74.0),
 (74.0),
 (71.0),
 (75.0),
 (75.0),
 (72.0),
 (69.0),
 (72.0),
 (74.0),
 (73.0),
 (64.0),
 (65.0),
 (68.0),
 (62.0),
 (58.0),
 (73.0),
 (60.0),
 (68.0),
 (76.0),
 (68.0),
 (66.0),
 (64.0),
 (64.0),
 (64.0),
 (76.0),
 (75.0),
 (68.0),
 (68.0),
 (72.0),
 (63.0),
 (68.0),
 (75.0),
 (65.0),
 (64.0),
 (68.0),
 (68.0),
 (66.0),
 (67.0),
 (64.0),
 (65.0),
 (75.0),
 (68.0),
 (71.0),
 (71.0),
 (71.0),
 (68.0),
 (68.0),
 (72.0),
 (70.0),
 (74.0),
 (67.0),
 (71.0),
 (71.0),
 (71.0),
 (74.0),
 (68.0),
 (71.0),
 (69.0),
 (69.0),
 (68.0),
 (68.0),
 (72.0),
 (74.0),
 (72.0),
 (69.0),
 (70.0),
 (72.0),
 (71.0),
 (71.0),
 (72.0),
 (70.0),
 (71.0),
 (76.0),
 (73.0),
 (74.0),
 (74.0),
 (74.0),
 (74.0),
 (74.0),
 (74.0),
 (73.0),
 (74.0),
 (74.0),
 (73.0),
 (74.0),
 (75.0),
 (74.0),
 (74.0),
 (75.0),
 (74.0),
 (75.0),
 (74.0),
 (70.0),
 (70.0),
 (70.0),
 (76.0),
 (76.0),
 (76.0),
 (76.0),
 (70.0),
 (77.0),
 (74.0),
 (73.0),
 (76.0),
 (76.0),
 (74.0),
 (77.0),
 (77.0),
 (78.0),
 (77.0),
 (77.0),
 (76.0),
 (77.0),
 (78.0),
 (76.0),
 (77.0),
 (77.0),
 (70.0),
 (76.0),
 (74.0),
 (72.0),
 (74.0),
 (73.0),
 (75.0),
 (75.0),
 (75.0),
 (76.0),
 (77.0),
 (78.0),
 (77.0),
 (78.0),
 (77.0),
 (76.0),
 (77.0),
 (79.0),
 (77.0),
 (74.0),
 (78.0),
 (77.0),
 (79.0),
 (78.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (73.0),
 (77.0),
 (78.0),
 (73.0),
 (70.0),
 (76.0),
 (77.0),
 (77.0),
 (77.0),
 (77.0),
 (78.0),
 (77.0),
 (77.0),
 (78.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (75.0),
 (76.0),
 (76.0),
 (77.0),
 (78.0),
 (76.0),
 (77.0),
 (75.0),
 (77.0),
 (77.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (76.0),
 (76.0),
 (77.0),
 (77.0),
 (77.0),
 (78.0),
 (77.0),
 (73.0),
 (77.0),
 (79.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (76.0),
 (77.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (77.0),
 (77.0),
 (78.0),
 (80.0),
 (77.0),
 (78.0),
 (77.0),
 (78.0),
 (76.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (79.0),
 (78.0),
 (78.0),
 (76.0),
 (78.0),
 (77.0),
 (79.0),
 (77.0),
 (77.0),
 (78.0),
 (77.0),
 (77.0),
 (78.0),
 (78.0),
 (79.0),
 (78.0),
 (78.0),
 (79.0),
 (76.0),
 (76.0),
 (78.0),
 (79.0),
 (79.0),
 (78.0),
 (77.0),
 (77.0),
 (73.0),
 (73.0),
 (77.0),
 (79.0),
 (77.0),
 (77.0),
 (85.0),
 (77.0),
 (76.0),
 (79.0),
 (79.0),
 (77.0),
 (77.0),
 (82.0),
 (80.0),
 (79.0),
 (78.0),
 (76.0),
 (77.0),
 (74.0),
 (77.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (80.0),
 (79.0),
 (75.0),
 (78.0),
 (79.0),
 (78.0),
 (77.0),
 (78.0),
 (77.0),
 (77.0),
 (78.0),
 (77.0),
 (76.0),
 (77.0),
 (76.0),
 (74.0),
 (78.0),
 (76.0),
 (77.0),
 (75.0),
 (74.0),
 (77.0),
 (76.0),
 (77.0),
 (73.0),
 (76.0),
 (75.0),
 (76.0),
 (71.0),
 (77.0),
 (77.0),
 (75.0),
 (76.0),
 (77.0),
 (78.0),
 (76.0),
 (76.0),
 (76.0),
 (74.0),
 (75.0),
 (76.0),
 (73.0),
 (71.0),
 (75.0),
 (76.0),
 (78.0),
 (76.0),
 (75.0),
 (76.0),
 (73.0),
 (75.0),
 (73.0),
 (70.0),
 (75.0),
 (73.0),
 (72.0),
 (72.0),
 (66.0),
 (69.0),
 (68.0),
 (73.0),
 (74.0),
 (73.0),
 (73.0),
 (73.0),
 (73.0),
 (71.0),
 (73.0),
 (73.0),
 (77.0),
 (72.0),
 (71.0),
 (73.0),
 (70.0),
 (73.0),
 (69.0),
 (74.0),
 (72.0),
 (71.0),
 (72.0),
 (72.0),
 (70.0),
 (73.0),
 (73.0),
 (72.0),
 (73.0),
 (73.0),
 (72.0),
 (63.0),
 (63.0),
 (66.0),
 (66.0),
 (74.0),
 (71.0),
 (65.0),
 (61.0),
 (71.0),
 (65.0),
 (66.0),
 (61.0),
 (74.0),
 (75.0),
 (75.0),
 (75.0),
 (68.0),
 (73.0),
 (74.0),
 (74.0),
 (67.0),
 (66.0),
 (69.0),
 (74.0),
 (68.0),
 (72.0),
 (72.0),
 (71.0),
 (71.0),
 (66.0),
 (72.0),
 (63.0),
 (65.0),
 (69.0),
 (71.0),
 (71.0),
 (65.0),
 (61.0),
 (71.0),
 (72.0),
 (72.0),
 (72.0),
 (65.0),
 (66.0),
 (73.0),
 (73.0),
 (71.0),
 (72.0),
 (73.0),
 (72.0),
 (73.0),
 (77.0),
 (67.0),
 (69.0),
 (73.0),
 (72.0),
 (73.0),
 (74.0),
 (73.0),
 (67.0),
 (71.0),
 (72.0),
 (67.0),
 (69.0),
 (67.0),
 (69.0),
 (66.0),
 (73.0),
 (74.0),
 (71.0),
 (72.0),
 (73.0),
 (71.0),
 (72.0),
 (73.0),
 (72.0),
 (73.0),
 (69.0),
 (73.0),
 (74.0),
 (72.0),
 (74.0),
 (74.0),
 (72.0),
 (70.0),
 (71.0),
 (72.0),
 (73.0),
 (74.0),
 (73.0),
 (74.0),
 (75.0),
 (74.0),
 (74.0),
 (74.0),
 (74.0),
 (74.0),
 (72.0),
 (69.0),
 (71.0),
 (70.0),
 (71.0),
 (70.0),
 (75.0),
 (75.0),
 (75.0),
 (75.0),
 (75.0),
 (75.0),
 (74.0),
 (69.0),
 (73.0),
 (73.0),
 (75.0),
 (74.0),
 (75.0),
 (76.0),
 (75.0),
 (75.0),
 (75.0),
 (75.0),
 (75.0),
 (75.0),
 (74.0),
 (75.0),
 (74.0),
 (75.0),
 (74.0),
 (74.0),
 (75.0),
 (75.0),
 (72.0),
 (74.0),
 (74.0),
 (75.0),
 (76.0),
 (77.0),
 (77.0),
 (77.0),
 (76.0),
 (77.0),
 (76.0),
 (78.0),
 (77.0),
 (76.0),
 (76.0),
 (77.0),
 (76.0),
 (76.0),
 (73.0),
 (76.0),
 (76.0),
 (75.0),
 (77.0),
 (77.0),
 (76.0),
 (78.0),
 (77.0),
 (76.0),
 (77.0),
 (76.0),
 (76.0),
 (77.0),
 (77.0),
 (78.0),
 (77.0),
 (77.0),
 (77.0),
 (76.0),
 (75.0),
 (76.0),
 (76.0),
 (77.0),
 (76.0),
 (73.0),
 (73.0),
 (75.0),
 (77.0),
 (76.0),
 (77.0),
 (76.0),
 (77.0),
 (74.0),
 (77.0),
 (77.0),
 (78.0),
 (76.0),
 (77.0),
 (77.0),
 (76.0),
 (76.0),
 (76.0),
 (77.0),
 (78.0),
 (77.0),
 (78.0),
 (78.0),
 (78.0),
 (75.0),
 (77.0),
 (76.0),
 (76.0),
 (79.0),
 (77.0),
 (77.0),
 (77.0),
 (77.0),
 (77.0),
 (73.0),
 (78.0),
 (78.0),
 (79.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (77.0),
 (77.0),
 (78.0),
 (78.0),
 (76.0),
 (75.0),
 (78.0),
 (78.0),
 (77.0),
 (79.0),
 (78.0),
 (78.0),
 (77.0),
 (76.0),
 (79.0),
 (77.0),
 (77.0),
 (78.0),
 (78.0),
 (78.0),
 (78.0),
 (73.0),
 (75.0),
 (78.0),
 (78.0),
 (78.0),
 (77.0),
 (76.0),
 (77.0),
 (77.0),
 (75.0),
 (77.0),
 (75.0),
 (78.0),
 (76.0),
 (77.0),
 (77.0),
 (76.0),
 (76.0),
 (78.0),
 (78.0),
 (77.0),
 (78.0),
 (71.0),
 (74.0),
 (76.0),
 (77.0),
 (77.0),
 (76.0),
 (77.0),
 (76.0),
 (76.0),
 (78.0),
 (78.0),
 (77.0),
 (75.0),
 (78.0),
 (74.0),
 (75.0),
 (77.0),
 (73.0),
 (73.0),
 (76.0),
 (78.0),
 (75.0),
 (75.0),
 (80.0),
 (78.0),
 (79.0),
 (78.0),
 (78.0),
 (77.0),
 (72.0),
 (75.0),
 (77.0),
 (78.0),
 (77.0),
 (76.0),
 (78.0),
 (78.0),
 (76.0),
 (76.0),
 (74.0),
 (77.0),
 (77.0),
 (76.0),
 (78.0),
 (71.0),
 (70.0),
 (74.0),
 (71.0),
 (69.0),
 (76.0),
 (77.0),
 (77.0),
 (76.0),
 (75.0),
 (76.0),
 (77.0),
 (77.0),
 (77.0),
 (75.0),
 (73.0),
 (74.0),
 (76.0),
 (75.0),
 (75.0),
 (71.0),
 (69.0),
 (71.0),
 (69.0),
 ...]

In [56]:
#making a range of dates to help myself a bit. thanks stackoverflow
startjun_16 = dt.datetime(2016, 6, 1)
endjun_16 = dt.datetime(2016, 6, 30)
startjun_17 = dt.datetime(2017, 6, 1)
endjun_17 = dt.datetime(2017, 6, 30)

jun_16_df = pd.date_range(startjun_16, endjun_16)
jun_17_df = pd.date_range(startjun_17, endjun_17)

#well this was a waste because the query can't parse this. shame. back to my original idea

DatetimeIndex(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
               '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
               '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
               '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
               '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
               '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
               '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
               '2016-06-29', '2016-06-30'],
              dtype='datetime64[ns]', freq='D')

In [152]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 
end_may16 = dt.date(2016, 5, 31)
end_may17 = dt.date(2017, 5, 31)
#ok lets give our list a go
#list didn't work BUT i found something better. a limit!
#jun_meas_16 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_may16).limit(30).all()
#jun_meas_17 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_may17).limit(30).all()
#the above is incredibly labor-intensive. which is WHY WE HAVE EXTRACT IN THE FIRST PLACE
#special shoutout to TA Nino Yosinao for saving my butt on this one. 

jun_meas = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date) == '06').all()

In [153]:
jun_meas

[('2010-06-01', 78.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 78.0),
 ('2010-06-04', 76.0),
 ('2010-06-05', 77.0),
 ('2010-06-06', 78.0),
 ('2010-06-07', 77.0),
 ('2010-06-08', 78.0),
 ('2010-06-09', 78.0),
 ('2010-06-10', 79.0),
 ('2010-06-11', 78.0),
 ('2010-06-12', 78.0),
 ('2010-06-13', 78.0),
 ('2010-06-14', 77.0),
 ('2010-06-15', 78.0),
 ('2010-06-16', 78.0),
 ('2010-06-17', 77.0),
 ('2010-06-18', 77.0),
 ('2010-06-19', 82.0),
 ('2010-06-20', 78.0),
 ('2010-06-21', 78.0),
 ('2010-06-22', 78.0),
 ('2010-06-23', 78.0),
 ('2010-06-24', 78.0),
 ('2010-06-25', 77.0),
 ('2010-06-26', 76.0),
 ('2010-06-27', 78.0),
 ('2010-06-28', 78.0),
 ('2010-06-29', 78.0),
 ('2010-06-30', 78.0),
 ('2011-06-01', 77.0),
 ('2011-06-02', 78.0),
 ('2011-06-03', 73.0),
 ('2011-06-04', 70.0),
 ('2011-06-05', 76.0),
 ('2011-06-06', 77.0),
 ('2011-06-07', 77.0),
 ('2011-06-08', 77.0),
 ('2011-06-09', 77.0),
 ('2011-06-10', 78.0),
 ('2011-06-11', 77.0),
 ('2011-06-12', 77.0),
 ('2011-06-13', 78.0),
 ('2011-06-14', 78.0),
 ('2011-06-15', 77.0),
 ('2011-06-17', 78.0),
 ('2011-06-18', 78.0),
 ('2011-06-19', 75.0),
 ('2011-06-20', 76.0),
 ('2011-06-21', 76.0),
 ('2011-06-24', 77.0),
 ('2011-06-25', 78.0),
 ('2011-06-26', 76.0),
 ('2011-06-27', 77.0),
 ('2011-06-28', 75.0),
 ('2011-06-29', 77.0),
 ('2012-06-01', 76.0),
 ('2012-06-02', 76.0),
 ('2012-06-03', 75.0),
 ('2012-06-04', 77.0),
 ('2012-06-05', 77.0),
 ('2012-06-06', 76.0),
 ('2012-06-07', 78.0),
 ('2012-06-08', 77.0),
 ('2012-06-09', 76.0),
 ('2012-06-10', 77.0),
 ('2012-06-11', 76.0),
 ('2012-06-12', 76.0),
 ('2012-06-13', 77.0),
 ('2012-06-14', 77.0),
 ('2012-06-15', 78.0),
 ('2012-06-16', 77.0),
 ('2012-06-17', 77.0),
 ('2012-06-18', 77.0),
 ('2012-06-19', 76.0),
 ('2012-06-20', 75.0),
 ('2012-06-21', 76.0),
 ('2012-06-22', 76.0),
 ('2012-06-23', 77.0),
 ('2012-06-24', 76.0),
 ('2012-06-25', 73.0),
 ('2012-06-26', 73.0),
 ('2012-06-27', 75.0),
 ('2012-06-28', 77.0),
 ('2012-06-29', 76.0),
 ('2012-06-30', 77.0),
 ('2013-06-01', 79.0),
 ('2013-06-02', 78.0),
 ('2013-06-03', 79.0),
 ('2013-06-04', 78.0),
 ('2013-06-05', 78.0),
 ('2013-06-06', 79.0),
 ('2013-06-07', 77.0),
 ('2013-06-08', 77.0),
 ('2013-06-09', 77.0),
 ('2013-06-10', 77.0),
 ('2013-06-11', 77.0),
 ('2013-06-12', 78.0),
 ('2013-06-13', 77.0),
 ('2013-06-14', 76.0),
 ('2013-06-15', 78.0),
 ('2013-06-16', 78.0),
 ('2013-06-17', 77.0),
 ('2013-06-18', 78.0),
 ('2013-06-19', 78.0),
 ('2013-06-20', 73.0),
 ('2013-06-21', 76.0),
 ('2013-06-22', 77.0),
 ('2013-06-23', 75.0),
 ('2013-06-24', 76.0),
 ('2013-06-25', 74.0),
 ('2013-06-26', 75.0),
 ('2013-06-27', 77.0),
 ('2013-06-28', 76.0),
 ('2013-06-29', 77.0),
 ('2013-06-30', 78.0),
 ('2014-06-01', 79.0),
 ('2014-06-02', 77.0),
 ('2014-06-03', 78.0),
 ('2014-06-04', 79.0),
 ('2014-06-05', 78.0),
 ('2014-06-06', 78.0),
 ('2014-06-07', 78.0),
 ('2014-06-08', 78.0),
 ('2014-06-09', 79.0),
 ('2014-06-10', 79.0),
 ('2014-06-11', 82.0),
 ('2014-06-12', 80.0),
 ('2014-06-13', 79.0),
 ('2014-06-14', 79.0),
 ('2014-06-15', 78.0),
 ('2014-06-16', 78.0),
 ('2014-06-17', 77.0),
 ('2014-06-18', 78.0),
 ('2014-06-19', 78.0),
 ('2014-06-20', 73.0),
 ('2014-06-21', 75.0),
 ('2014-06-22', 75.0),
 ('2014-06-23', 76.0),
 ('2014-06-24', 84.0),
 ('2014-06-25', 79.0),
 ('2014-06-26', 76.0),
 ('2014-06-27', 79.0),
 ('2014-06-28', 79.0),
 ('2014-06-29', 77.0),
 ('2014-06-30', 79.0),
 ('2015-06-01', 78.0),
 ('2015-06-02', 78.0),
 ('2015-06-03', 79.0),
 ('2015-06-04', 77.0),
 ('2015-06-05', 79.0),
 ('2015-06-06', 78.0),
 ('2015-06-07', 78.0),
 ('2015-06-08', 78.0),
 ('2015-06-09', 79.0),
 ('2015-06-10', 77.0),
 ('2015-06-11', 78.0),
 ('2015-06-12', 78.0),
 ('2015-06-13', 78.0),
 ('2015-06-14', 78.0),
 ('2015-06-15', 79.0),
 ('2015-06-16', 79.0),
 ('2015-06-17', 77.0),
 ('2015-06-18', 78.0),
 ('2015-06-19', 78.0),
 ('2015-06-20', 78.0),
 ('2015-06-21', 79.0),
 ('2015-06-22', 79.0),
 ('2015-06-23', 77.0),
 ('2015-06-24', 79.0),
 ('2015-06-25', 79.0),
 ('2015-06-26', 79.0),
 ('2015-06-27', 81.0),
 ('2015-06-28', 76.0),
 ('2015-06-29', 80.0),
 ('2015-06-30', 78.0),
 ('2016-06-01', 76.0),
 ('2016-06-02', 71.0),
 ('2016-06-03', 71.0),
 ('2016-06-04', 74.0),
 ('2016-06-05', 76.0),
 ('2016-06-06', 78.0),
 ('2016-06-07', 77.0),
 ('2016-06-08', 77.0),
 ('2016-06-09', 73.0),
 ('2016-06-10', 77.0),
 ('2016-06-11', 78.0),
 ('2016-06-12', 78.0),
 ('2016-06-13', 80.0),
 ('2016-06-14', 79.0),
 ('2016-06-15', 78.0),
 ('2016-06-16', 77.0),
 ('2016-06-17', 76.0),
 ('2016-06-18', 77.0),
 ('2016-06-19', 77.0),
 ('2016-06-20', 78.0),
 ('2016-06-21', 80.0),
 ('2016-06-22', 79.0),
 ('2016-06-23', 79.0),
 ('2016-06-24', 77.0),
 ('2016-06-25', 78.0),
 ('2016-06-26', 79.0),
 ('2016-06-27', 80.0),
 ('2016-06-28', 76.0),
 ('2016-06-29', 79.0),
 ('2016-06-30', 80.0),
 ('2017-06-01', 79.0),
 ('2017-06-02', 79.0),
 ('2017-06-03', 79.0),
 ('2017-06-04', 79.0),
 ('2017-06-05', 80.0),
 ('2017-06-06', 79.0),
 ('2017-06-07', 79.0),
 ('2017-06-08', 80.0),
 ('2017-06-09', 80.0),
 ('2017-06-10', 77.0),
 ('2017-06-11', 79.0),
 ('2017-06-12', 83.0),
 ('2017-06-13', 80.0),
 ('2017-06-14', 80.0),
 ('2017-06-15', 78.0),
 ('2017-06-16', 79.0),
 ('2017-06-17', 80.0),
 ('2017-06-18', 77.0),
 ('2017-06-19', 80.0),
 ('2017-06-20', 78.0),
 ('2017-06-21', 79.0),
 ('2017-06-22', 80.0),
 ('2017-06-23', 78.0),
 ('2017-06-24', 80.0),
 ('2017-06-25', 80.0),
 ('2017-06-26', 81.0),
 ('2017-06-27', 80.0),
 ('2017-06-28', 79.0),
 ('2017-06-29', 79.0),
 ('2017-06-30', 75.0),
 ('2010-06-01', 74.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 75.0),
 ('2010-06-04', 75.0),
 ('2010-06-05', 74.0),
 ('2010-06-06', 75.0),
 ('2010-06-07', 75.0),
 ('2010-06-08', 75.0),
 ('2010-06-09', 75.0),
 ('2010-06-10', 75.0),
 ('2010-06-11', 83.0),
 ('2010-06-12', 75.0),
 ('2010-06-13', 76.0),
 ('2010-06-14', 73.0),
 ('2010-06-15', 74.0),
 ('2010-06-16', 74.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 70.0),
 ('2010-06-19', 74.0),
 ('2010-06-20', 75.0),
 ('2010-06-21', 75.0),
 ('2010-06-22', 75.0),
 ('2010-06-23', 75.0),
 ('2010-06-24', 75.0),
 ('2010-06-25', 74.0),
 ('2010-06-26', 72.0),
 ('2010-06-27', 76.0),
 ('2010-06-28', 73.0),
 ('2010-06-29', 75.0),
 ('2010-06-30', 76.0),
 ('2011-06-01', 74.0),
 ('2011-06-02', 75.0),
 ('2011-06-03', 71.0),
 ('2011-06-04', 69.0),
 ('2011-06-05', 69.0),
 ('2011-06-06', 74.0),
 ('2011-06-07', 71.0),
 ('2011-06-08', 74.0),
 ('2011-06-09', 74.0),
 ('2011-06-10', 75.0),
 ('2011-06-11', 73.0),
 ('2011-06-12', 73.0),
 ('2011-06-13', 73.0),
 ('2011-06-14', 75.0),
 ('2011-06-15', 75.0),
 ('2011-06-16', 74.0),
 ('2011-06-17', 74.0),
 ('2011-06-18', 75.0),
 ('2011-06-19', 74.0),
 ('2011-06-20', 73.0),
 ('2011-06-21', 72.0),
 ('2011-06-22', 74.0),
 ('2011-06-23', 72.0),
 ('2011-06-24', 75.0),
 ('2011-06-25', 76.0),
 ('2011-06-26', 74.0),
 ('2011-06-27', 74.0),
 ('2011-06-28', 74.0),
 ('2011-06-29', 74.0),
 ('2011-06-30', 74.0),
 ('2012-06-01', 71.0),
 ('2012-06-02', 71.0),
 ('2012-06-03', 75.0),
 ('2012-06-04', 72.0),
 ('2012-06-05', 72.0),
 ('2012-06-06', 73.0),
 ('2012-06-07', 73.0),
 ('2012-06-08', 73.0),
 ('2012-06-09', 74.0),
 ('2012-06-10', 73.0),
 ('2012-06-11', 72.0),
 ('2012-06-12', 72.0),
 ('2012-06-13', 70.0),
 ('2012-06-14', 72.0),
 ('2012-06-15', 72.0),
 ('2012-06-16', 72.0),
 ('2012-06-17', 74.0),
 ('2012-06-18', 73.0),
 ('2012-06-19', 73.0),
 ('2012-06-20', 70.0),
 ('2012-06-21', 73.0),
 ('2012-06-22', 72.0),
 ('2012-06-23', 73.0),
 ('2012-06-24', 69.0),
 ('2012-06-25', 72.0),
 ('2012-06-26', 71.0),
 ('2012-06-27', 71.0),
 ('2012-06-28', 73.0),
 ('2012-06-29', 73.0),
 ('2012-06-30', 72.0),
 ('2013-06-01', 75.0),
 ('2013-06-02', 75.0),
 ('2013-06-03', 75.0),
 ('2013-06-04', 75.0),
 ('2013-06-05', 74.0),
 ('2013-06-06', 74.0),
 ('2013-06-07', 74.0),
 ('2013-06-08', 75.0),
 ('2013-06-09', 75.0),
 ('2013-06-10', 74.0),
 ('2013-06-11', 75.0),
 ('2013-06-12', 75.0),
 ('2013-06-13', 74.0),
 ('2013-06-14', 72.0),
 ('2013-06-15', 74.0),
 ('2013-06-16', 74.0),
 ('2013-06-17', 74.0),
 ('2013-06-18', 74.0),
 ('2013-06-19', 74.0),
 ('2013-06-20', 72.0),
 ('2013-06-21', 70.0),
 ('2013-06-22', 75.0),
 ('2013-06-23', 74.0),
 ('2013-06-24', 71.0),
 ('2013-06-25', 71.0),
 ('2013-06-26', 70.0),
 ('2013-06-27', 73.0),
 ('2013-06-28', 71.0),
 ('2013-06-29', 71.0),
 ('2013-06-30', 77.0),
 ('2014-06-01', 77.0),
 ('2014-06-02', 74.0),
 ('2014-06-03', 73.0),
 ('2014-06-04', 75.0),
 ('2014-06-05', 75.0),
 ('2014-06-06', 74.0),
 ('2014-06-07', 74.0),
 ('2014-06-08', 75.0),
 ('2014-06-09', 75.0),
 ('2014-06-10', 72.0),
 ('2014-06-11', 74.0),
 ('2014-06-12', 76.0),
 ('2014-06-13', 76.0),
 ('2014-06-14', 75.0),
 ('2014-06-15', 75.0),
 ('2014-06-16', 74.0),
 ('2014-06-17', 72.0),
 ('2014-06-18', 74.0),
 ('2014-06-19', 75.0),
 ('2014-06-20', 70.0),
 ('2014-06-21', 71.0),
 ('2014-06-22', 72.0),
 ('2014-06-23', 71.0),
 ('2014-06-24', 73.0),
 ('2014-06-25', 74.0),
 ('2014-06-26', 72.0),
 ('2014-06-27', 74.0),
 ('2014-06-28', 76.0),
 ('2014-06-29', 72.0),
 ('2014-06-30', 75.0),
 ('2015-06-03', 75.0),
 ('2015-06-04', 72.0),
 ('2015-06-05', 70.0),
 ('2015-06-06', 76.0),
 ('2015-06-07', 78.0),
 ('2015-06-08', 72.0),
 ('2015-06-09', 74.0),
 ('2015-06-10', 74.0),
 ('2015-06-11', 72.0),
 ('2015-06-12', 71.0),
 ('2015-06-13', 79.0),
 ('2015-06-14', 79.0),
 ('2015-06-15', 76.0),
 ('2015-06-16', 75.0),
 ('2015-06-17', 72.0),
 ('2015-06-18', 74.0),
 ('2015-06-19', 76.0),
 ('2015-06-20', 76.0),
 ('2015-06-21', 77.0),
 ('2015-06-22', 75.0),
 ('2015-06-23', 76.0),
 ('2015-06-24', 75.0),
 ('2015-06-25', 75.0),
 ('2015-06-26', 76.0),
 ('2015-06-27', 76.0),
 ('2015-06-29', 74.0),
 ('2016-06-01', 70.0),
 ('2016-06-02', 69.0),
 ('2016-06-03', 70.0),
 ('2016-06-04', 68.0),
 ('2016-06-05', 70.0),
 ('2016-06-06', 74.0),
 ('2016-06-07', 75.0),
 ('2016-06-08', 74.0),
 ('2016-06-09', 71.0),
 ('2016-06-10', 73.0),
 ('2016-06-11', 75.0),
 ('2016-06-12', 74.0),
 ('2016-06-13', 76.0),
 ('2016-06-14', 76.0),
 ('2016-06-15', 76.0),
 ('2016-06-16', 76.0),
 ('2016-06-17', 75.0),
 ('2016-06-18', 75.0),
 ('2016-06-19', 75.0),
 ('2016-06-20', 74.0),
 ('2016-06-21', 73.0),
 ('2016-06-22', 76.0),
 ('2016-06-23', 74.0),
 ('2016-06-24', 78.0),
 ('2016-06-25', 71.0),
 ('2016-06-26', 75.0),
 ('2016-06-27', 75.0),
 ('2016-06-28', 74.0),
 ('2016-06-29', 77.0),
 ('2016-06-30', 77.0),
 ('2017-06-01', 76.0),
 ('2017-06-02', 76.0),
 ('2017-06-03', 76.0),
 ('2017-06-04', 78.0),
 ('2017-06-05', 76.0),
 ('2017-06-06', 75.0),
 ('2017-06-07', 75.0),
 ('2017-06-08', 76.0),
 ('2017-06-09', 78.0),
 ('2017-06-10', 75.0),
 ('2017-06-11', 73.0),
 ('2017-06-12', 76.0),
 ('2017-06-13', 76.0),
 ('2017-06-14', 76.0),
 ('2017-06-15', 77.0),
 ('2017-06-16', 76.0),
 ('2017-06-17', 77.0),
 ('2017-06-18', 72.0),
 ('2017-06-19', 77.0),
 ('2017-06-20', 75.0),
 ('2017-06-21', 82.0),
 ('2017-06-22', 77.0),
 ('2017-06-23', 76.0),
 ('2017-06-24', 74.0),
 ('2017-06-25', 73.0),
 ('2017-06-26', 77.0),
 ('2017-06-27', 77.0),
 ('2017-06-28', 77.0),
 ('2017-06-29', 76.0),
 ('2017-06-30', 74.0),
 ('2010-06-01', 73.0),
 ('2010-06-02', 72.0),
 ('2010-06-03', 74.0),
 ('2010-06-04', 73.0),
 ('2010-06-05', 72.0),
 ('2010-06-06', 75.0),
 ('2010-06-07', 74.0),
 ('2010-06-08', 75.0),
 ('2010-06-09', 73.0),
 ('2010-06-10', 75.0),
 ('2010-06-11', 76.0),
 ('2010-06-12', 74.0),
 ('2010-06-13', 74.0),
 ('2010-06-14', 73.0),
 ('2010-06-15', 73.0),
 ('2010-06-16', 76.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 70.0),
 ('2010-06-19', 75.0),
 ('2010-06-20', 73.0),
 ('2010-06-21', 74.0),
 ('2010-06-22', 74.0),
 ('2010-06-23', 74.0),
 ('2010-06-24', 74.0),
 ('2010-06-25', 70.0),
 ('2010-06-27', 75.0),
 ('2010-06-28', 74.0),
 ('2010-06-29', 73.0),
 ('2010-06-30', 74.0),
 ('2011-06-01', 72.0),
 ('2011-06-02', 73.0),
 ('2011-06-03', 67.0),
 ('2011-06-04', 69.0),
 ('2011-06-05', 76.0),
 ('2011-06-06', 73.0),
 ('2011-06-07', 70.0),
 ('2011-06-08', 72.0),
 ('2011-06-09', 74.0),
 ('2011-06-10', 72.0),
 ('2011-06-13', 72.0),
 ('2011-06-14', 75.0),
 ('2011-06-15', 73.0),
 ('2011-06-16', 73.0),
 ('2011-06-17', 72.0),
 ('2011-06-18', 74.0),
 ('2011-06-19', 76.0),
 ('2011-06-21', 72.0),
 ('2011-06-22', 74.0),
 ('2011-06-23', 70.0),
 ('2011-06-24', 74.0),
 ('2011-06-25', 74.0),
 ('2011-06-27', 74.0),
 ('2011-06-28', 71.0),
 ('2012-06-21', 75.0),
 ('2012-06-22', 75.0),
 ('2012-06-24', 76.0),
 ('2012-06-25', 77.0),
 ('2012-06-26', 75.0),
 ('2012-06-27', 74.0),
 ('2012-06-28', 75.0),
 ('2012-06-29', 76.0),
 ('2012-06-30', 78.0),
 ('2013-06-03', 78.0),
 ('2013-06-04', 76.0),
 ('2013-06-05', 78.0),
 ('2013-06-06', 76.0),
 ('2013-06-07', 76.0),
 ('2013-06-08', 78.0),
 ('2013-06-09', 79.0),
 ('2013-06-10', 77.0),
 ('2013-06-11', 76.0),
 ('2013-06-12', 77.0),
 ('2013-06-13', 77.0),
 ('2013-06-14', 76.0),
 ('2013-06-16', 78.0),
 ('2013-06-17', 76.0),
 ('2013-06-18', 76.0),
 ('2013-06-19', 77.0),
 ('2013-06-20', 71.0),
 ('2013-06-25', 74.0),
 ('2013-06-26', 72.0),
 ('2013-06-27', 77.0),
 ('2014-06-01', 77.0),
 ('2014-06-02', 78.0),
 ('2014-06-03', 77.0),
 ('2014-06-04', 77.0),
 ('2014-06-05', 76.0),
 ('2014-06-06', 75.0),
 ('2014-06-07', 79.0),
 ('2014-06-09', 75.0),
 ('2014-06-10', 73.0),
 ('2014-06-11', 76.0),
 ('2014-06-12', 78.0),
 ('2014-06-13', 77.0),
 ('2014-06-14', 78.0),
 ('2014-06-16', 76.0),
 ('2014-06-17', 75.0),
 ('2014-06-18', 76.0),
 ('2014-06-19', 77.0),
 ('2014-06-20', 74.0),
 ('2014-06-21', 78.0),
 ('2014-06-23', 77.0),
 ('2014-06-24', 77.0),
 ('2014-06-25', 74.0),
 ('2014-06-26', 74.0),
 ('2014-06-27', 78.0),
 ('2014-06-29', 79.0),
 ('2014-06-30', 79.0),
 ('2015-06-01', 78.0),
 ('2015-06-03', 75.0),
 ('2015-06-04', 76.0),
 ('2015-06-05', 78.0),
 ('2015-06-06', 78.0),
 ('2015-06-08', 74.0),
 ('2015-06-09', 78.0),
 ('2015-06-10', 77.0),
 ('2015-06-11', 76.0),
 ('2015-06-12', 78.0),
 ('2015-06-14', 78.0),
 ('2015-06-15', 78.0),
 ('2015-06-16', 78.0),
 ('2015-06-17', 74.0),
 ('2015-06-18', 79.0),
 ('2015-06-19', 77.0),
 ('2015-06-20', 73.0),
 ('2015-06-21', 79.0),
 ('2015-06-22', 79.0),
 ('2015-06-23', 78.0),
 ('2015-06-24', 77.0),
 ('2015-06-25', 78.0),
 ('2015-06-26', 78.0),
 ('2015-06-27', 80.0),
 ('2015-06-28', 80.0),
 ('2015-06-29', 79.0),
 ('2015-06-30', 74.0),
 ('2016-06-01', 71.0),
 ('2016-06-02', 74.0),
 ('2016-06-03', 75.0),
 ('2016-06-07', 75.0),
 ('2016-06-08', 74.0),
 ('2016-06-09', 76.0),
 ('2016-06-10', 75.0),
 ('2016-06-11', 77.0),
 ('2016-06-12', 77.0),
 ('2016-06-13', 79.0),
 ('2016-06-14', 79.0),
 ('2016-06-15', 78.0),
 ('2016-06-16', 79.0),
 ('2016-06-17', 73.0),
 ('2016-06-18', 78.0),
 ('2016-06-19', 79.0),
 ('2016-06-20', 80.0),
 ('2016-06-21', 76.0),
 ('2016-06-22', 79.0),
 ('2016-06-23', 79.0),
 ('2016-06-24', 77.0),
 ('2016-06-25', 80.0),
 ('2016-06-26', 79.0),
 ('2016-06-27', 78.0),
 ('2016-06-28', 78.0),
 ('2016-06-29', 79.0),
 ('2016-06-30', 78.0),
 ('2017-06-01', 81.0),
 ('2017-06-02', 78.0),
 ('2017-06-03', 80.0),
 ('2017-06-04', 79.0),
 ('2017-06-05', 81.0),
 ('2017-06-06', 80.0),
 ('2017-06-07', 81.0),
 ('2017-06-08', 79.0),
 ('2017-06-09', 81.0),
 ('2017-06-10', 78.0),
 ('2017-06-11', 79.0),
 ('2017-06-12', 79.0),
 ('2017-06-13', 75.0),
 ('2017-06-14', 79.0),
 ('2017-06-15', 78.0),
 ('2017-06-16', 80.0),
 ('2017-06-17', 78.0),
 ('2017-06-18', 77.0),
 ('2017-06-19', 78.0),
 ('2017-06-20', 79.0),
 ('2017-06-23', 76.0),
 ('2017-06-26', 80.0),
 ('2017-06-29', 76.0),
 ('2017-06-30', 81.0),
 ('2010-06-01', 77.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 77.0),
 ('2010-06-04', 75.0),
 ('2010-06-07', 76.0),
 ('2010-06-08', 79.0),
 ('2010-06-09', 79.0),
 ('2010-06-10', 77.0),
 ('2010-06-15', 76.0),
 ('2010-06-16', 77.0),
 ('2010-06-17', 76.0),
 ('2010-06-18', 73.0),
 ('2010-06-21', 76.0),
 ('2010-06-22', 77.0),
 ('2010-06-23', 77.0),
 ('2010-06-24', 78.0),
 ('2010-06-25', 77.0),
 ('2010-06-28', 76.0),
 ('2010-06-29', 78.0),
 ('2010-06-30', 78.0),
 ('2011-06-01', 75.0),
 ('2011-06-02', 77.0),
 ('2011-06-03', 65.0),
 ('2011-06-06', 76.0),
 ('2011-06-07', 74.0),
 ('2011-06-08', 76.0),
 ('2011-06-09', 76.0),
 ('2011-06-13', 77.0),
 ('2011-06-14', 77.0),
 ('2011-06-15', 76.0),
 ('2011-06-16', 77.0),
 ('2011-06-17', 76.0),
 ('2011-06-20', 77.0),
 ('2011-06-21', 74.0),
 ('2011-06-22', 76.0),
 ('2011-06-23', 73.0),
 ('2011-06-24', 75.0),
 ('2011-06-27', 76.0),
 ('2011-06-28', 75.0),
 ('2011-06-29', 76.0),
 ('2011-06-30', 75.0),
 ('2012-06-01', 74.0),
 ('2012-06-04', 74.0),
 ('2012-06-05', 74.0),
 ('2012-06-06', 74.0),
 ('2012-06-07', 76.0),
 ('2012-06-08', 76.0),
 ('2012-06-12', 77.0),
 ('2012-06-13', 77.0),
 ('2012-06-14', 78.0),
 ('2012-06-15', 73.0),
 ('2012-06-18', 75.0),
 ('2012-06-19', 72.0),
 ('2012-06-20', 76.0),
 ('2012-06-21', 76.0),
 ('2012-06-22', 73.0),
 ('2012-06-25', 74.0),
 ('2012-06-26', 72.0),
 ('2012-06-27', 76.0),
 ('2012-06-28', 76.0),
 ('2012-06-29', 76.0),
 ('2013-06-03', 78.0),
 ('2013-06-04', 78.0),
 ('2013-06-05', 78.0),
 ('2013-06-06', 78.0),
 ('2013-06-07', 75.0),
 ('2013-06-10', 77.0),
 ('2013-06-12', 73.0),
 ('2013-06-13', 78.0),
 ('2013-06-14', 75.0),
 ('2013-06-17', 73.0),
 ('2013-06-18', 77.0),
 ('2013-06-19', 80.0),
 ('2013-06-20', 70.0),
 ('2013-06-21', 78.0),
 ('2013-06-25', 72.0),
 ('2013-06-26', 78.0),
 ('2013-06-27', 72.0),
 ('2013-06-28', 78.0),
 ('2014-06-02', 77.0),
 ('2014-06-03', 79.0),
 ('2014-06-04', 77.0),
 ('2014-06-05', 78.0),
 ('2014-06-06', 74.0),
 ('2014-06-09', 79.0),
 ('2014-06-10', 79.0),
 ('2014-06-12', 79.0),
 ('2014-06-13', 79.0),
 ('2014-06-16', 77.0),
 ('2014-06-17', 79.0),
 ('2014-06-18', 78.0),
 ('2014-06-19', 80.0),
 ('2014-06-20', 81.0),
 ('2014-06-27', 81.0),
 ('2015-06-10', 78.0),
 ('2015-06-12', 77.0),
 ('2015-06-15', 78.0),
 ('2015-06-16', 79.0),
 ('2015-06-17', 77.0),
 ('2015-06-18', 79.0),
 ('2015-06-19', 80.0),
 ('2015-06-22', 79.0),
 ('2015-06-23', 78.0),
 ('2015-06-24', 79.0),
 ('2015-06-25', 79.0),
 ('2015-06-29', 79.0),
 ('2015-06-30', 81.0),
 ('2016-06-01', 64.0),
 ('2016-06-02', 65.0),
 ('2016-06-03', 75.0),
 ('2016-06-06', 76.0),
 ('2016-06-07', 78.0),
 ('2016-06-08', 77.0),
 ('2016-06-09', 75.0),
 ('2016-06-13', 78.0),
 ('2016-06-14', 81.0),
 ('2016-06-15', 78.0),
 ('2016-06-16', 76.0),
 ('2016-06-17', 73.0),
 ('2016-06-20', 74.0),
 ('2016-06-21', 76.0),
 ('2016-06-22', 78.0),
 ('2016-06-23', 79.0),
 ('2016-06-24', 78.0),
 ('2016-06-27', 72.0),
 ('2016-06-28', 78.0),
 ('2016-06-29', 80.0),
 ('2016-06-30', 81.0),
 ('2017-06-02', 79.0),
 ('2017-06-05', 78.0),
 ('2017-06-06', 80.0),
 ('2017-06-07', 80.0),
 ('2017-06-08', 78.0),
 ('2017-06-09', 80.0),
 ('2017-06-13', 81.0),
 ('2017-06-14', 78.0),
 ('2017-06-15', 77.0),
 ('2017-06-16', 78.0),
 ('2017-06-19', 78.0),
 ('2017-06-20', 77.0),
 ('2017-06-21', 76.0),
 ('2017-06-22', 81.0),
 ('2017-06-23', 76.0),
 ('2017-06-26', 82.0),
 ('2017-06-27', 80.0),
 ('2017-06-28', 80.0),
 ('2017-06-29', 79.0),
 ('2017-06-30', 74.0),
 ('2010-06-01', 69.0),
 ('2010-06-02', 70.0),
 ('2010-06-03', 67.0),
 ('2010-06-04', 70.0),
 ('2010-06-05', 73.0),
 ('2010-06-06', 73.0),
 ('2010-06-09', 72.0),
 ('2010-06-10', 72.0),
 ('2010-06-11', 77.0),
 ('2010-06-12', 70.0),
 ('2010-06-13', 78.0),
 ('2010-06-15', 73.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 70.0),
 ('2010-06-19', 74.0),
 ('2010-06-20', 77.0),
 ('2010-06-22', 69.0),
 ('2010-06-23', 73.0),
 ('2010-06-24', 73.0),
 ('2010-06-25', 74.0),
 ('2010-06-28', 73.0),
 ('2010-06-29', 72.0),
 ('2010-06-30', 75.0),
 ('2011-06-08', 73.0),
 ('2011-06-09', 76.0),
 ('2011-06-12', 74.0),
 ('2011-06-13', 76.0),
 ('2011-06-14', 73.0),
 ('2011-06-15', 76.0),
 ('2011-06-16', 76.0),
 ('2011-06-20', 78.0),
 ('2011-06-21', 75.0),
 ('2011-06-22', 77.0),
 ('2012-06-01', 75.0),
 ('2012-06-14', 73.0),
 ('2012-06-21', 76.0),
 ('2012-06-26', 71.0),
 ('2012-06-29', 71.0),
 ('2010-06-01', 76.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 76.0),
 ('2010-06-04', 73.0),
 ('2010-06-05', 78.0),
 ('2010-06-06', 77.0),
 ('2010-06-07', 77.0),
 ('2010-06-08', 77.0),
 ('2010-06-09', 78.0),
 ('2010-06-10', 78.0),
 ('2010-06-11', 76.0),
 ('2010-06-12', 76.0),
 ('2010-06-13', 79.0),
 ('2010-06-14', 74.0),
 ('2010-06-15', 75.0),
 ('2010-06-16', 76.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 73.0),
 ('2010-06-19', 76.0),
 ('2010-06-20', 78.0),
 ('2010-06-21', 76.0),
 ('2010-06-22', 79.0),
 ('2010-06-23', 77.0),
 ('2010-06-24', 76.0),
 ('2010-06-25', 74.0),

In [154]:
jun_df = pd.DataFrame(jun_meas)
jun_df

            date  tobs
0     2010-06-01  78.0
1     2010-06-02  76.0
2     2010-06-03  78.0
3     2010-06-04  76.0
4     2010-06-05  77.0
...          ...   ...
1695  2017-06-26  79.0
1696  2017-06-27  74.0
1697  2017-06-28  74.0
1698  2017-06-29  76.0
1699  2017-06-30  75.0

[1700 rows x 2 columns]

In [92]:
#this is a fun relic of another long walk for another short drink. leaving it in so when i look back i'll remember how this works
#temp_df = jun16_df.merge(jun17_df, how='outer')
#temp_df['date'] = temp_df['date'].apply(lambda x: dt.datetime.strptime(x, '%Y-%m-%d'))
#temp_df.dtypes

date    datetime64[ns]
tobs           float64
dtype: object

In [93]:
#temp_df.head(4)

        date  tobs
0 2016-06-01  76.0
1 2016-06-02  71.0
2 2016-06-03  71.0
3 2016-06-04  74.0

In [155]:
#oh wow. if i knew this was a step i wouldn't have bothered with all that conversion. oops
#  3. Convert the June temperatures to a list.
juntemp = [temp for temp in jun_df['tobs']]

In [160]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
juntemp_df = pd.DataFrame(juntemp)
juntemp_df

         0
0     78.0
1     76.0
2     78.0
3     76.0
4     77.0
...    ...
1695  79.0
1696  74.0
1697  74.0
1698  76.0
1699  75.0

[1700 rows x 1 columns]

In [157]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.
juntemp_df.describe()

                 0
count  1700.000000
mean     74.944118
std       3.257417
min      64.000000
25%      73.000000
50%      75.000000
75%      77.000000
max      85.000000

## D2: Determine the Summary Statistics for December

In [136]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.
end_nov16 = dt.date(2016, 11, 30)
end_nov15 = dt.date(2015, 11, 30)
end_nov14 = dt.date(2014, 11, 30)
end_nov13 = dt.date(2013, 11, 30)
end_nov12 = dt.date(2012, 11, 30)
end_nov11 = dt.date(2011, 11, 30)
end_nov10 = dt.date(2010, 11, 30)
dec_meas_16 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov16).limit(31).all()
#lmao the data stops before the next december. i am all over it with the unneccessary steps
#dec_meas_17 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov17).limit(30).all()
#i'm in office hours right now to ask how to make this more sufficient, but for now let's iterate through these
dec_meas_15 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov15).limit(31).all()
dec_meas_14 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov14).limit(31).all()
dec_meas_13 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov13).limit(31).all()
dec_meas_12 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov12).limit(30).all()
dec_meas_11 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov11).limit(31).all()
dec_meas_10 = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date > end_nov10).limit(25).all()
#i can't help but think i could have made this a function somehow, but i don't have time for that right now

In [137]:
dec16df = pd.DataFrame(dec_meas_16)
dec15df = pd.DataFrame(dec_meas_15)
dec14df = pd.DataFrame(dec_meas_14)
dec13df = pd.DataFrame(dec_meas_13)
dec12df = pd.DataFrame(dec_meas_12)
dec11df = pd.DataFrame(dec_meas_11)
dec10df = pd.DataFrame(dec_meas_10)

In [139]:
dec12df.tail(4)

          date  tobs
26  2012-12-28  65.0
27  2012-12-29  64.0
28  2012-12-30  69.0
29  2012-12-31  68.0

In [140]:
dec_m1 = dec16df.merge(dec15df, how='outer')
dec_m2 = dec_m1.merge(dec14df, how='outer')
dec_m3 = dec_m2.merge(dec13df, how='outer')
dec_m4 = dec_m3.merge(dec12df, how='outer')
dec_m5 = dec_m4.merge(dec11df, how='outer')
dec_df = dec_m5.merge(dec10df, how='outer')

In [141]:
dec_df.head(4)

         date  tobs
0  2016-12-01  75.0
1  2016-12-02  72.0
2  2016-12-03  69.0
3  2016-12-04  71.0

In [142]:
dec_df.tail(4)

           date  tobs
206  2010-12-28  71.0
207  2010-12-29  75.0
208  2010-12-30  75.0
209  2010-12-31  72.0

In [161]:
#well that was a super fun labor-intensive way to do it. let's use our handy new friend extract
dec_meas = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date) == '12').all()

In [164]:
dec_meas_df = pd.DataFrame(dec_meas)

In [165]:
# 7. Convert the December temperatures to a list.
dectemp = [temp for temp in dec_meas_df['tobs']]

In [166]:
# 8. Create a DataFrame from the list of temperatures for the month of December. 
dectemp_df = pd.DataFrame(dectemp)

In [167]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
dectemp_df.describe()

                 0
count  1517.000000
mean     71.041529
std       3.745920
min      56.000000
25%      69.000000
50%      71.000000
75%      74.000000
max      83.000000

In [168]:
juntemp_df.describe()

                 0
count  1700.000000
mean     74.944118
std       3.257417
min      64.000000
25%      73.000000
50%      75.000000
75%      77.000000
max      85.000000